### ISSUE TITLE
Another Unhandled promise rejection

### ISSUE THREAD

**Issue by Jokurilism** [Hermitter/BDO-Boss-Alerts#5]
(node:1784) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: Incorrect login details were provided.

Any suggest for this error? i'm using bot_id either from right-click -> copy id and copy paste the Token bot none of them were worked

**Comment by Hermitter** [comment]
The only time I see this error is when the login details are wrong. Did you add the right [Bot Token](https://camo.githubusercontent.com/c98a5bcc47b6518c3bfed40d716ef896fd0fd3c8/68747470733a2f2f6861636b737465722e696d6769782e6e65742f75706c6f6164732f6174746163686d656e74732f3337363338312f325f5865584f354c4777514a2e706e673f6175746f3d636f6d7072657373253243666f726d617426773d36383026683d353130266669743d6d6178) to [config.json](https://github.com/Hermitter/BDO-Boss-Alerts/blob/master/config.json#L2)?

**Comment by Jokurilism** [comment]
strange but it works, i've reset the token and try again with the new token and the error has changed like this:

Logged Into Server
E:\nodejs\BDO-Boss-Alerts-master\app.js:18
  channel.send("Looking Out For BDO Boss Spawns...");
          ^

TypeError: Cannot read property 'send' of undefined
    at Client.bot.on (E:\nodejs\BDO-Boss-Alerts-master\app.js:18:11)
    at emitNone (events.js:111:20)
    at Client.emit (events.js:208:7)
    at WebSocketConnection.triggerReady (E:\nodejs\BDO-Boss-Alerts-master\node_m
odules\discord.js\src\client\websocket\WebSocketConnection.js:123:17)
    at WebSocketConnection.checkIfReady (E:\nodejs\BDO-Boss-Alerts-master\node_m
odules\discord.js\src\client\websocket\WebSocketConnection.js:139:61)
    at GuildCreateHandler.handle (E:\nodejs\BDO-Boss-Alerts-master\node_modules\
discord.js\src\client\websocket\packets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (E:\nodejs\BDO-Boss-Alerts-master\node_modu
les\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (E:\nodejs\BDO-Boss-Alerts-master\node_modul
es\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (E:\nodejs\BDO-Boss-Alerts-master\node_modu
les\discord.js\src\client\websocket\WebSocketConnection.js:293:17)
    at WebSocket.onMessage (E:\nodejs\BDO-Boss-Alerts-master\node_modules\ws\lib
\event-target.js:120:16)

is this something related to bot permission in channel-chat?

**Comment by Hermitter** [comment]
Seems like it. Try making a fresh Discord server and test the bot there.

**Comment by Hermitter** [comment]
Due to no activity, I will be closing the issue.
